"""
Django settings for dailyFresh project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6xtvbdbm^e01avr&jv)l1^g&igw!m1!l!p8c2ez377cdn__33$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'goods',
    'cart',
    'tinymce',
    'haystack',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dailyFresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyFresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'192.168.0.106',
        'PORT':'3306',
        'USER':'root',
        'PASSWORD':'123',
        'NAME': 'dailyfresh',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]

#富文本编辑器设置
TINYMCE_DEFAULT_CONFIG = {
    'theme':'advanced',
    'width':600,
    'height':400,
}

#全文搜索引擎
HAYSTACK_CONNECTIONS = {
    'default':{
        'ENGINE':'haystack.backends.whoosh_cn_backend.WhooshEngine',
        'PATH':os.path.join(BASE_DIR,'whoosh_index')
    }
}
#自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
#logging module
from logging.handlers import SysLogHandler
LOGGING = {
    'version':1,
    'disable_existing_loggers':False,  #是否禁用所有的已存在的日志配置

    'formatters':{  #设定日志格式
        'standard':{
            'format':'%(asctime)s [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s- %(message)s]'}
    },

    'filters':{  #过滤器
        'require_debug_false':{
            '()':'django.utils.log.RequireDebugFalse',
        }
    },

    'handlers':{  #处理器
        'null':{
            'level':'DEBUG',
            'class':'logging.NullHandler',
        },
        'mail_admin':{  #发送邮件
            'level':'ERROR',
            'class':'django.utils.log.AdminEmailHandler',
            'filters':['require_debug_false'],  #仅当DEBUG=false时才发送邮件.这里引用的是上边那个filters
            'include_html':True
        },
        'debug':{  #记录到日志文件
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'encoding':'utf-8',
            'filename':os.path.join(BASE_DIR,'log','debug.log'),#日志输出文件
            'maxBytes':1024*1024*5, #文件大小
            'backupCount':2,  #备份份数
            'formatter':'standard',  #使用的日志格式
        },
        'console':{#输出到控制台
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter':'standard'
        },
    },

    'loggers':{#logging管理器..这里采用了三种日志记录方式，分别是django---将日志信息输出到文件，django.request---将信息输出到控制台
        'django_file':{
            'handlers':['debug'],
            'level':'DEBUG',
            'propagate':False
        },
        'django_console':{
            'handlers':['console'],
            'level':'INFO',
            'propagate':True,
         },
        #对于不在ALLOWED_HOSTS中的请求不发送邮件
        'django.security.DisallowedHost':{
            'handlers':['null'],
            'propagate':False,
        }
     }

}


