# Generated by Django 2.2 on 2019-05-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
    ]
