# Generated by Django 2.2 on 2019-05-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0004_auto_20190519_2306'),
        ('user', '0002_auto_20190519_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userInfo')),
            ],
            options={
                'verbose_name': '购物车商品信息',
                'verbose_name_plural': '购物车商品信息',
            },
        ),
    ]
